# Лабораторная работа №1
## Выполнил студент группы БСТ1904 Сошников СВ
### Задание №1
Вывод оглавление и выполнение print(“Hello, World!”)

In [1]:
print("Hello, World!")

Hello, World!


### Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер
матрицы, а min_lim и max_lim - минимальное и максимальное значение для
генерируемого числа . По умолчанию при отсутствии параметров принимать следующие
значения:
m = 50
n = 50
min_limit = -250
max_limit = 1000 + (номер своего варианта)

In [2]:
import numpy as np
import time
import random
try:
    m = int(input("Введите количество строк m "))
except ValueError:
    m = 50
try:
    n = int(input("Введите число столбцов n "))
except ValueError:
    n = 50
try:
    min_lim = int(input("Введите минимальное число min_lim "))
except ValueError:
    min_lim  = -250
try:
    max_lim = int(input("Введите максимальное число max_lim "))
except ValueError:
    max_lim = 1018
A = np.empty((m, n))
for i in range(m):
    for j in range(n):
        A[i, j] = random.randint(min_lim, max_lim)
print("Ваш массив: ")
print(A)

Введите количество строк m 3
Введите число столбцов n 3
Введите минимальное число min_lim -10
Введите максимальное число max_lim 61
Ваш массив: 
[[36. 49. 47.]
 [36. -8. -6.]
 [ 0.  9.  5.]]


## Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [3]:
%%time
def Vibor(Arr): 
    for i in range(0, len(Arr) - 1): 
        for j in range(i + 1, len(Arr)): 
            if Arr[j] < Arr[i]: 
                Arr[i], Arr[j] = Arr[j], Arr[i]

import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1
Vibor(B)
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)

[[-8. -6.  0.]
 [ 5.  9. 36.]
 [36. 47. 49.]]
Wall time: 8.01 ms


In [4]:
%%time
import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1
B.sort()
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)

[[-8. -6.  0.]
 [ 5.  9. 36.]
 [36. 47. 49.]]
Wall time: 2 ms
